version: "3.9"
services:
  webapp:
    container_name: todo_list
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=todo_list;Username=postgres2;Password=strong_password
    depends_on:
       db:
         condition: service_healthy
  db:
    container_name: todo_list_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo_list
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: strong_password
    volumes:
      - postgres_data_todo_list:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres2 -d todo_list"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data_todo_list:

